### PR TITLE
Fix: Reduce excessive recentering

### PR DESCRIPTION
**Pull request by cizl**

### CODE REVIEW

**Review by tonilastre — APPROVED** [review]
I feel like you have the same changes again (partially). Have you pulled new/simulator-fixes before.
I am talking about `zoomIn` and `zoomOut` functions.

**Comment by cizl** [comment]
> I feel like you have the same changes again (partially). Have you pulled new/simulator-fixes before. I am talking about `zoomIn` and `zoomOut` functions.

I noticed. I just wanted to push it to GH to better see changes, that's why i put it in the draft. But something here is out of whack. Yesterday I had issues with github not picking up changes that I pushed.

**Comment by cizl** [comment]
@tonilastre I have no idea what's going on with GH.

on `new/simulator-fixes`, there is only the following commit:
* `New: Add zoom and recenter functions` (`faa9eed`)

But in the already [closed PR](https://github.com/memgraph/orb/pull/74) it looks like 2 commits should have been merged:
* `New: Add zoom and recenter functions` (`faa9eed`)
* `Fix: reuse this.render` (`54d87c6`)

And now, this PR tries to add everything??

**Comment by tonilastre** [comment]
Yep, that is strange, but I see it good now on the UI.

Btw even the hash of the commit is different. But that might be due to the Squash + Merge.

Btw this is approved, all good here.

**Pull request merged**
